plugins {
    id 'fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    flatDir {
        dirs 'libs'
    }
    maven { url "https://bmclapi2.bangbang93.com/maven" }
    maven { url "https://maven.aliyun.com/repository/public" }
    maven { url "https://maven.fabricmc.net/" }
    maven { url "https://masa.dy.fi/maven/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation name: 'litematica-fabric-1.21-0.19.60'
    modImplementation name: 'malilib-fabric-1.21-0.21.10'
    modCompileOnly name: 'modmenu-11.0.3'
    modLocalRuntime name: 'modmenu-11.0.3'

}